### ISSUE TITLE
[Feature Request] Standalone Docker Image

### ISSUE THREAD

**Issue by emmm-dee** [stakater/GitWebhookProxy#60]
Hello, nice tool. 

It would be great if you had a Docker image ready-to-go with your software. I currently run regular Docker not Kubernetes so it would be nice to have something to work with.

**Comment by waseem-h** [comment]
@emmm-dee The documentation may not have been clear but we do have ready to run docker images that are deployed on kubernetes via our manifests. They are located here: https://hub.docker.com/r/stakater/gitwebhookproxy/tags
You can simply run it via the following docker command
```
docker run stakater/gitwebhookproxy:v0.2.63 -listen :8080 -upstreamURL google.com -provider github -secret "test"
```

**Comment by ahmadiq** [comment]
This has been incorporated in the [README](https://github.com/stakater/GitWebhookProxy#running-outside-kubernetes).

@emmm-dee please close the issue if your requirement is satisfied. Thanks.

**Comment by emmm-dee** [comment]
Thanks very much all, this is great.
