### ISSUE TITLE
Possibility to whitelist webhooks ip addresses

### ISSUE THREAD

**Issue by azkore** [stakater/GitWebhookProxy#62]
In the case of GitHub, would it be possible to add an option to query GitHub api for IP ranges used by webhooks and only allow access from them? It seems like the most secure option.

Don't know what's the situation with GitLab, but maybe they have similar API.

**Comment by antonpiatek-imanage** [comment]
You could always achieve this with your own firewall rules

**Comment by davidkarlsen** [comment]
also if you expose the webhook with ngrok or similar they have a whitelist option.

**Comment by rasheedamir** [comment]
yes and we suggest to add firewall rules in the ingress controller

I don't think we should add this feature in GWP! it can be handled at one level above
