### ISSUE TITLE
Can't handle if Github PR is labelled

### ISSUE THREAD

**Issue by nareshnayini** [stakater/GitWebhookProxy#72]
`2019/10/01 20:52:19 Received event type: pull_request
2019/10/01 20:52:19 Github payload unmarshaling failed for Pull Request event: json: cannot unmarshal object into Go struct field .labels of type string
2019/10/01 20:52:19 Incoming request from user:
2019/10/01 20:52:19 Ignoring request for user:`

**Comment by kahootali** [comment]
@nareshnayini Can you create a PR with your updated payload?

**Comment by nareshnayini** [comment]
@kahootali do you mean PR in this repo https://github.com/stakater/GitWebhookProxy ?

**Comment by kahootali** [comment]
Yes

**Comment by nareshnayini** [comment]
hey, If you mean by creating a PR with a fix for this - sorry, I don't have `go` programming language. But I can share the payload if that helps. Let me know.

**Comment by kahootali** [comment]
@nareshnayini  Can you please deploy with the image version, `stakater/gitwebhookproxy:SNAPSHOT-PR-73-1` and let us know if it works for you?

**Comment by nareshnayini** [comment]
@kahootali Verified with this image version with PR having both Label as well as Team reviewer. It's working fine in both cases now. Thank you.

**Comment by waseem-h** [comment]
Closing this. Fixed by #73
