### ISSUE TITLE
unmarshaling failed for Pull Request event: invalid character 'p' looking for beginning of value

### ISSUE THREAD

**Issue by jrobison-sb** [stakater/GitWebhookProxy#88]
I'm running `stakater/gitwebhookproxy:v0.2.75` with `GWP_SECRET` exposed as an environment variable and with this command passed into docker: 
```
        "-allowedPaths", "/events",
        "-upstreamURL", "http://MY_UPSTREAM_HOSTNAME:8080",
```

When I trigger a webhook at GitHub, the hook isn't proxied as expected, with this error shown in the logs:
```
Github payload unmarshaling failed for Push event: invalid character 'p' looking for beginning of value
```

What is going wrong here?

**Comment by w32-blaster** [comment]
Seeing the same error. @jrobison-sb have you found a solution for this issue?

**Comment by jrobison-sb** [comment]
@w32-blaster unfortunately my solution/workaround was to use a different proxy software.

**Comment by w32-blaster** [comment]
Any recommandation? :)

**Comment by w32-blaster** [comment]
Hey @jrobison-sb , I just figured out what was wrong with my config. You have to make sure that the webhook content type is application/json. That will solve the above issue.

**Comment by jrobison-sb** [comment]
@w32-blaster oh, cool, thanks for the update.

Since this was apparently just user error on my part, I'll close this issue now.
